### ISSUE TITLE
JsonSyntaxException

### ISSUE THREAD

**Issue by beihaifeiwu** [chengpohi/elasticshell#26]
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonObject; at path $
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1010)
	at com.github.chengpohi.util.JsonUtil.parseJsonArr(JsonUtil.java:399)
	at com.github.chengpohi.api.TransformAPI.lambda$static$1(TransformAPI.java:27)
	at com.github.chengpohi.util.ExecuteResult.extract(ExecuteResult.java:129)
	at com.github.chengpohi.api.RunApi.run(RunApi.java:49)
	at com.github.chengpohi.ui.tree.node.EDQLTransformsNode$1.run(EDQLTransformsNode.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by chengpohi** [comment]
Hi @beihaifeiwu , could you send ES version?

**Comment by chengpohi** [comment]
and could you directly execute request:

```
GET /_cat/transforms?format=json
```

and paste the response.

**Comment by chengpohi** [comment]
Hi @beihaifeiwu , this issue is fixed in version [v1.9.22](https://github.com/chengpohi/edql/releases/tag/v1.9.22)
this issue is caused es5 incompatible issue

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [v1.9.22](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/versions/stable/324287)
