### ISSUE TITLE
BUG: JSON view does not display anything

### ISSUE THREAD

**Issue by JeroenTriptic** [chengpohi/elasticshell#38]
When I do a simple query I get the results nicely displayed in the table but if I want to see the raw JSON response I only get a blank window.
![image](https://github.com/chengpohi/edql/assets/60502147/9feb1ed2-6d64-4c07-aaf1-b1a397ae0d53)
![image](https://github.com/chengpohi/edql/assets/60502147/52ea55cf-55ae-40ea-baf6-55f0898c2dd5)

**Comment by chengpohi** [comment]
Hi @JeroenTriptic got it, maybe this is caused json data parsed failed, I will try to reproduce it and fix it in next version

**Comment by chengpohi** [comment]
reproduced, this is caused by json viewer will try to format json data, but we have set the json viewer ready only, since format json and json viewer concurrently initing, so in some time if set `ready only` firstly, and format secondly this issue produced.

```
com.intellij.openapi.editor.impl.DocumentImpl$UnexpectedBulkUpdateStateException: Current operation is not permitted in bulk mode, see Document.isInBulkUpdate() javadoc
	at com.intellij.openapi.editor.impl.DocumentImpl.assertNotInBulkUpdate(DocumentImpl.java:1214)
	at com.intellij.openapi.editor.impl.view.EditorView.assertNotInBulkMode(EditorView.java:730)
	at com.intellij.openapi.editor.impl.view.EditorView.visualLineToY(EditorView.java:160)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.getPreferredHeight(EditorSizeManager.java:315)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.getPreferredSize(EditorSizeManager.java:286)
	at com.intellij.openapi.editor.impl.view.EditorView.getPreferredSize(EditorView.java:292)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$getPreferredSize$27(EditorImpl.java:2195)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.editor.impl.EditorImpl.getPreferredSize(EditorImpl.java:2191)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.getPreferredSize(EditorComponentImpl.java:204)
	at java.desktop/javax.swing.JViewport.getViewSize(JViewport.java:1118)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI.syncScrollPaneWithViewport(BasicScrollPaneUI.java:335)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1168)
	at java.desktop/javax.swing.JViewport.fireStateChanged(JViewport.java:1494)
	at java.desktop/javax.swing.JViewport$ViewListener.componentResized(JViewport.java:1413)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6483)
	at java.desktop/java.awt.Component.processEvent(Component.java:6437)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1509)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:786)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:870)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by chengpohi** [comment]
Hi @JeroenTriptic  please try the latest version: [v1.10.3](https://github.com/chengpohi/edql/releases/tag/v1.10.3), and also you can download from Jetbrains market [v1.10.3](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/457477)

Thanks your feedback, If you meet any issue please let me know.
